test-jsjsref:
  stage: test
  before_script:
  - git submodule update --init lib/test262
  - opam switch 4.02.1
  - eval `opam config env`
  - cd jsjsref
  - make test_init
  script:
  - make test
  except:
  - triggers

git-sync:
  script:
  - eval `ssh-agent`
  - echo "$PUSH_KEY" | ssh-add -
  - git sync-remote git@github.com:resource-reasoning/jscert_dev.git git@gitlab.doc.ic.ac.uk:resource-reasoning/jscert_dev.git
  - ssh-agent -k
  only:
  - triggers
