language: c    # Not really, but close enough

env:
  - PPA=ocaml41
  - PPA=ocaml42

before_install:
  # Use an ubuntu ppa coq build to speed things up
  - sudo add-apt-repository -y ppa:grand-edgemaster/coq-$PPA
  - sudo add-apt-repository -y ppa:avsm/$PPA+opam12
  - sudo apt-get update
  - make init

install:
  - sudo apt-get install opam ocaml-native-compilers coq camlp4-extra
  - opam init -y
  - eval `opam config env`
  - make install_optional_depend

script:
  - make

